### ISSUE TITLE
🐛 RN 0.71.4 run-android ==> Task :react-native-vision-camera:compileDebugKotlin FAILED

### ISSUE THREAD

**Issue by thuantvDr4** [cuvent/react-native-vision-camera#1547]
### What were you trying to do?

I am trying to install this library

 "react-native-vision-camera": "2.15.4",
   "react": "18.2.0",
    "react-native": "0.71.4",

### What happened instead?

> Task :react-native-vision-camera:compileDebugKotlin FAILED

### Relevant log output

```shell
FAILURE: Build completed with 2 failures.

> Task :react-native-vision-camera:compileDebugKotlin FAILED

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-vision-camera:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 44s
```

### Device

android

### VisionCamera Version

2.15.4

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by Lonoyaa** [comment]
Hi, have you try running assembleRelease with --info for more detail
I'm just happened to work with the same version of dependencies as you but mine's fine. Did you try adding kotlinVersion and kotlin-gradle-plugin to android/build.gradle? if so, what version is it? mine is 1.6.20

**Comment by roberto497** [comment]
Same problem!

**Comment by zzz08900** [comment]
Probably related https://github.com/gradle/gradle/issues/21116#issuecomment-1228005104
gradle 7.3.3 works all fine here.

**Comment by Ho3ein-Boka** [comment]
same problem

**Comment by EstebanFuentealba** [comment]
changing kotlin version worked for me

```gradle
/*
/android/build.gradle
*/
buildscript {
    ext {
    // ...
        kotlinVersion = "1.6.20"
    }
    // ...
}
```

**Comment by thuantvDr4** [comment]
thanks all !

**Comment by CodingWithNobody** [comment]
Try this https://www.youtube.com/watch?v=8QW5HDa4lQU&list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i&index=67

**Comment by diamont1001** [comment]
> changing kotlin version worked for me
> 
> ```groovy-gradle
> /*
> /android/build.gradle
> */
> buildscript {
>     ext {
>     // ...
>         kotlinVersion = "1.6.20"
>     }
>     // ...
> }
> ```

it works, thank you!

**Comment by adelbeke** [comment]
Hello, any workaround without downgrading the Kotlin version ?

I really need to use the `1.8.0` version of Kotlin

**Comment by matiz87** [comment]
@adscud 
The problem is deprecated `kotlin-android-extension`
Workaround:
from file `android/build.gradle` remove 2 lines:
`classpath "org.jetbrains.kotlin:kotlin-android-extensions:$kotlin_version"`
&
`apply plugin: 'kotlin-android-extensions'`
and change lines
`if (REACT_NATIVE_VERSION >= 71) {
    buildFeatures {
      prefab true
    }
  }`
to
`buildFeatures {
    viewBinding = true
    if (REACT_NATIVE_VERSION >= 71) {
      prefab true
    }
  }`
After this you could prepare patch using patch-package. Working in my app.

**Comment by myselfuser1** [comment]
Try this https://www.youtube.com/playlist?list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i

**Comment by kigh143** [comment]
i am getting the same issue with version 0.65 RN

**Comment by mrousavy** [comment]
Hey! I've rewritten the entire Android codebase of VisionCamera from CameraX to Camera2 in the efforts of [✨ VisionCamera V3](https://github.com/mrousavy/react-native-vision-camera/issues/1376).

I just now completed the Camera2 rewrite and I believe the core structure is running, but there might be some edge cases to iron out. Can you try and test the PR #1674 for me to see if you can still reproduce this issue here?

Here's an instruction on how you can test that: https://github.com/mrousavy/react-native-vision-camera/pull/1674#issuecomment-1684104217

If the issue cannot be reproduced with that version/PR anymore, then hoorayy, I fixed it! 🎉 
Otherwise please let me know and I'll keep this issue open to keep track of it.

Thank you!

**Comment by xts-bit** [comment]
@mrousavy This issue is still coming on V3.2 latest one on Andriod

**Comment by ISnowFoxI** [comment]
Removing `kotlinVersion` from `build.gradle` fixed the issue for me. I added it because of another library if I remember correctly. You could also try the `build.gradle` code from the example.

https://github.com/mrousavy/react-native-vision-camera/blob/main/package/example/android/build.gradle#L5-L10

**Comment by tatiana-grange** [comment]
Hello !

@mrousavy This issue is still coming on V3.6.4 on android

* React Native => 0.71.14
* Reanimated => 3.5.4

````
buildscript {
    ext {
        buildToolsVersion = "33.0.0"
        minSdkVersion = 28
        compileSdkVersion = 33
        targetSdkVersion = 33
        supportLibVersion = "28.0.0"
        kotlinVersion = "1.6.20"
        ndkVersion = "23.1.7779620"
````
![Capture d’écran 2023-10-30 à 17 54 55](https://github.com/mrousavy/react-native-vision-camera/assets/90247712/24b683f3-514f-4ae6-8088-01a3b1cc8c38)

**Comment by tatiana-grange** [comment]
Hi !
I changed `kotlinVersion` for 1.7.20 and this is now working !

Current working for react-native-vision-camera@3.6.4 and react-native@0.71.14 :

````
buildscript {
    ext {
        buildToolsVersion = "33.0.0"
        minSdkVersion = 28
        compileSdkVersion = 33
        targetSdkVersion = 33
        supportLibVersion = "28.0.0"
        kotlinVersion = "1.7.20"
        ndkVersion = "23.1.7779620"
````

**Comment by ShuraRB** [comment]
Changing the `kotlinVersion` to 1.7.20 also worked for me!!

```
ext {
        kotlinVersion = "1.7.20"
        ...
    }
```
and
```
dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.20"
        ...
}
```

**Comment by kelrvins** [comment]
> Hi ! I changed `kotlinVersion` for 1.7.20 and this is now working !
> 
> Current working for react-native-vision-camera@3.6.4 and react-native@0.71.14 :
> 
> ```
> buildscript {
>     ext {
>         buildToolsVersion = "33.0.0"
>         minSdkVersion = 28
>         compileSdkVersion = 33
>         targetSdkVersion = 33
>         supportLibVersion = "28.0.0"
>         kotlinVersion = "1.7.20"
>         ndkVersion = "23.1.7779620"
> ```

Thank you very much, I spent three days on this issue

**Comment by robertyulisman** [comment]
> Hi ! I changed `kotlinVersion` for 1.7.20 and this is now working !
> 
> Current working for react-native-vision-camera@3.6.4 and react-native@0.71.14 :
> 
> ```
> buildscript {
>     ext {
>         buildToolsVersion = "33.0.0"
>         minSdkVersion = 28
>         compileSdkVersion = 33
>         targetSdkVersion = 33
>         supportLibVersion = "28.0.0"
>         kotlinVersion = "1.7.20"
>         ndkVersion = "23.1.7779620"
> ```

its work fine for me, thanks so much @tatiana-lonestone

**Comment by zahid502** [comment]
Hi, added some code in node_modules of react-native-vision-camera and it's worked for me.
**react-native 0.74.1**

**path**: node_modules/react-native-vision-camera/android/src/main/java/com/mrousavy/camera/frameprocessors/VisionCameraProxy.kt

`import com.facebook.react.common.annotations.FrameworkAPI//<--import here...
@OptIn(FrameworkAPI::class)//<--insert here`

<img width="1189" alt="Screenshot 2024-06-10 at 10 19 30 PM" src="https://github.com/mrousavy/react-native-vision-camera/assets/115239786/daa51432-788d-4591-b696-6af7f7ad66e1">

**Comment by mbalazy** [comment]
> Hi, added some code in node_modules of react-native-vision-camera and it's worked for me. **react-native 0.74.1**
> 
> **path**: node_modules/react-native-vision-camera/android/src/main/java/com/mrousavy/camera/frameprocessors/VisionCameraProxy.kt
> 
> `import com.facebook.react.common.annotations.FrameworkAPI//<--import here... @OptIn(FrameworkAPI::class)//<--insert here`
> 
> <img alt="Screenshot 2024-06-10 at 10 19 30 PM" width="1189" src="https://private-user-images.githubusercontent.com/115239786/338282720-daa51432-788d-4591-b696-6af7f7ad66e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMzc5NDUsIm5iZiI6MTcyNDIzNzY0NSwicGF0aCI6Ii8xMTUyMzk3ODYvMzM4MjgyNzIwLWRhYTUxNDMyLTc4OGQtNDU5MS1iNjk2LTZhZjdmN2FkNjZlMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMVQxMDU0MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOTI4ZTRmNGMzMTg1NzU3MzNmZjYwZGI2Y2FiYWI5NDVhMjAyYjQxMGM4NTllYjRiMDM4MjVhODYyMGY5NjAwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.M3tWXKNY9WnfUJGxczf4GO8i0zMHPDSu_YUQs69J5Nk">

thanks!

I created a diff for that:

```diff
diff --git a/node_modules/react-native-vision-camera/android/src/main/java/com/mrousavy/camera/frameprocessor/VisionCameraProxy.kt b/node_modules/react-native-vision-camera/android/src/main/java/com/mrousavy/camera/frameprocessor/VisionCameraProxy.kt
index 81bd1af..dbe53be 100644
--- a/node_modules/react-native-vision-camera/android/src/main/java/com/mrousavy/camera/frameprocessor/VisionCameraProxy.kt
+++ b/node_modules/react-native-vision-camera/android/src/main/java/com/mrousavy/camera/frameprocessor/VisionCameraProxy.kt
@@ -12,7 +12,9 @@ import com.facebook.react.uimanager.UIManagerHelper
 import com.mrousavy.camera.CameraView
 import com.mrousavy.camera.core.ViewNotFoundError
 import java.lang.ref.WeakReference
+import com.facebook.react.common.annotations.FrameworkAPI
 
+@OptIn(FrameworkAPI::class)
 @Suppress("KotlinJniMissingFunction") // we use fbjni.
 class VisionCameraProxy(private val reactContext: ReactApplicationContext) {
   companion object {

```

**Comment by davidburson** [comment]
With RNVC 4.6.3, after upgrading from RN 0.74.2 to RN 0.77.0 per https://react-native-community.github.io/upgrade-helper/?from=0.74.2&to=0.77.0, I am getting this error when I run `react-native run-android` on Windows (haven't tried on macOS).  I note that the RN 0.77.0 upgrade moves KotlinVersion to 2.0.21, not sure if that is a problem for RNVC?

`> Task :react-native-vision-camera:compileDebugKotlin FAILED`

```
error Failed to install the app. Command failed with exit code 1: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
No modules to process in combine-js-to-schema-cli. If this is unexpected, please check if you set up your NativeComponent correctly. See combine-js-to-schema.js for how codegen finds modules.

```

**Comment by banezr94** [comment]
Same issue for me, using the latest version of RN.

**Comment by davidburson** [comment]
@banezr94 I ran this script:
`"clean-after-rn-upgrade": "node -e \"fs.rmSync('./node_modules', { recursive: true, force: true })\" && pnpm store prune && pnpm install && cd android && gradlew clean && cd .. && react-native start --reset-cache",`

Then the patch mentioned in these got me past this issue:
https://github.com/mrousavy/react-native-vision-camera/issues/3389
https://github.com/mrousavy/react-native-vision-camera/pull/3382/files
https://github.com/mrousavy/react-native-vision-camera/issues/3380

But now I have this issue: https://github.com/mrousavy/react-native-vision-camera/issues/2862

So I may just wait until RN 0.78.0 and the next version of RNVC:  https://github.com/mrousavy/react-native-vision-camera/issues/2614#issuecomment-2625112161

**Comment by SKHRAPP** [comment]
@mrousavy Any update from this issue I using latest RN 0.77.0 getting this error

**Comment by digitalbore** [comment]
Same problem here.

"react-native": "0.77.0",
"react-native-vision-camera": "^4.6.3"

kotlinVersion = "2.0.21"
