### ISSUE TITLE
🐛 Android: NFC not working after Camera is unmounted

### ISSUE THREAD

**Issue by ldstein** [cuvent/react-native-vision-camera#516]
### What were you trying to do?

A couple of our Android test handsets are unable to simultaneously receive data from the camera and NFC reader.

This is not that unusual. In some cases it's done to limit interference caused by the NFC chip when capturing images. In other cases, it's a limitation of the underlying hardware (number of pathways, SPI channels, etc).

https://stackoverflow.com/questions/34607168/nfc-unavailable-when-camera-is-open
https://stackoverflow.com/questions/68636728/usage-of-camera-blocks-nfc-reading-writing

For the affected handsets, when using RNVC, we noticed NFC remains permanently blocked after the Camera component is unmounted. 

NFC starts working again after:

- Changing focus to a different app, then returning.
- Closing then relaunching the App.
- Fire an intent to start MainActivity with flags `ACTIVITY_NEW_TASK` and `FLAG_ACTIVITY_CLEAR_TASK`.

I think it's related to RNVC because we have tested a different camera component which does not exhibit this issue. 

My hunch is maybe the Camera is not being fully released after the component is unmounted?

App here for testing simultaneous NFC + Camera access: https://github.com/ldstein/MeshCameraTest/tree/nfc-test

### Reproduceable Code

```tsx
See repo
```

### What happened instead?

No crashes, no errors. Just no response from NFC reader.

### Device

Huawei VOC-L29 P30 Pro (Android 10), Xiaomi Redmi Note 9 Pro (Android 10 M2007JI7C)

### VisionCamera Version

2.9.1

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
well that's a weird one for sure. Thank you for the detailed report and reproduceable sample!

I'll try to take a look at this soon, but last time I checked, the Camera component unmounts and cleans up correctly. 🤔

**Comment by kojoo112** [comment]
```
import {BackHandler} from 'react-native';

const [isActive, setIsActive] = useState(true);

useEffect(() => {
const getPermission = async () => {
const status = await Camera.requestCameraPermission();
setHasPermission(status === 'authorized');
};

const backAction = () => {
  setIsActive(false);
};

const backHandler = BackHandler.addEventListener(
  'hardwareBackPress',
  backAction,
);

getPermission();

return () => {
  backHandler.remove();
};
}, []);
```
i had a same problem, try this. it works!

**Comment by Chenbao2021** [comment]
I have just meet the same problem with an old samsung modele . But when i using a Redmi that works well . So i guess some model is incompatible to use nfc and camera in same time .

**Comment by florinr** [comment]
Had the same problem on Samsung M33. I was using RNVC with frame processor to scan QR, and after to trigger NFC technology. For me it worked to set isActive as false on `<Camera>` before trying NFC. 
```    
          <Camera
            style={styles.camera}
            device={device}
            isActive={active}
            frameProcessor={frameProcessor}
            frameProcessorFps={2}
          />
```

**Comment by sommcz** [comment]
I've the same problem on Android 13 devices (A12 is not affected). Devices tested: Samsung E22, Samsung Flip 3 (A13), SamsungA13 5G.... 

Settings isActive to false works only when screen with camera is shown at the time when prop is set. If isActive is to false in screen's blur event, NFC is still blocked (probably because Camera behave differently when it is in view/out of view).

**Comment by alexrififi** [comment]
I confirm, on Samsung s20 ultra.
It helped setting `isActive` to false before closing the camera

**Comment by mrousavy** [comment]
Hey! I've rewritten the entire Android codebase of VisionCamera from CameraX to Camera2 in the efforts of [✨ VisionCamera V3](https://github.com/mrousavy/react-native-vision-camera/issues/1376).

I just now completed the Camera2 rewrite and I believe the core structure is running, but there might be some edge cases to iron out. Can you try and test the PR #1674 for me to see if you can still reproduce this issue here?

Here's an instruction on how you can test that: https://github.com/mrousavy/react-native-vision-camera/pull/1674#issuecomment-1684104217

If the issue cannot be reproduced with that version/PR anymore, then hoorayy, I fixed it! 🎉 
Otherwise please let me know and I'll keep this issue open to keep track of it.

Thank you!

**Comment by sommcz** [comment]
I've tested this issue with V3  + codescanner & simple frameprocessor (instead of previous vision-camera-code-scanner frameprocessor) and NFC works normally without any workarounds/hacks. It looks fixed, good job!

**Comment by pasquale95** [comment]
I still experience this problem with V3.
As soon as the Camera is mounted, the NFC reader stops working. Setting **isActive** does not solve the problem.
Any hint for solutions?

Few useful info:
- the problem does not happen if I use RNVC V2;
- the problem appears as soon as I render the `<Camera>` component;
- setting `isActive` to false or forcing to unmount the Camera does not solve the issue.

**Comment by mrousavy** [comment]
> the problem does not happen if I use RNVC V2;

Are you sure? The original poster said this problem happens on 2.9.x.

I believe this is just a Camera2 problem?

**Comment by mrousavy** [comment]
Hey! I just found out that I really forgot to close and dispose the locked Camera resources, so I just fixed that in this PR: https://github.com/mrousavy/react-native-vision-camera/pull/2174 
Now the Camera fully & synchronously closes all resources (CameraSession, CameraDevice, OpenGL context, Video & Photo outputs, Photo Synchronizer) once the view gets removed from the React view hierarchy ("unmounted"), and things like Flash, Torch, NFC, and other Camera components should be working again.

There is still a small issue that causes once Camera component to turn into a blackscreen when navigating back and forth between two Camera components, that's a pretty rare edge case but I will still try to fix that soon when I have some free time.


If you appreciate my time, expertise and dedication to this project, pleas [💖 consider sponsoring me on GitHub 💖](https://github.com/sponsors/mrousavy) to support the development of this project.

**Comment by undestructable100** [comment]
can any1 of you fux actually give a proper and understandable solution or you uncapable of doing it?

**Comment by mrousavy** [comment]
> We are not all computer programmers.

You are not a programmer but are commenting on a programming library?

> can any1 of you fux

whoops my finger slipped on the block & ban button

**Comment by namaikatiputkatapedal** [comment]
> > We are not all computer programmers.
> 
> You are not a programmer but are commenting on a programming library?
> 
> > can any1 of you fux
> 
> whoops my finger slipped on the block & ban button



Dumbass no1 is talkin to you

**Comment by namaikatiputkatapedal** [comment]
> > We are not all computer programmers.
> 
> You are not a programmer but are commenting on a programming library?
> 
> > can any1 of you fux
> 
> whoops my finger slipped on the block & ban button

![big-cock-and-balls](https://github.com/user-attachments/assets/5febeafd-1f53-4267-a878-f8ac763e4d49)


This for you

**Comment by mrousavy** [comment]
> Dumbass no1 is talkin to you

whoooops my finger slipped on the block & ban button again
