### ISSUE TITLE
Error: Exception in HostFunction: com.mrousavy.camera.ViewNotFoundError🐛 

### ISSUE THREAD

**Issue by fabio-C** [cuvent/react-native-vision-camera#810]
### What were you trying to do?

My Android app is in production and is using **react-native-vision-camera** with a custom **frameProcessor**.

I am receiving several crashes error notification from Google Play Console (100 crashes in the last 72hours).

I attach one:
![Screenshot_2022-02-08-18-20-25-032_com google android apps playconsole](https://user-images.githubusercontent.com/53861680/153042089-146dd993-2600-4831-9643-fe4b0d1f6d63.jpg)

Do you know why this is happening?
Can be a problem with my custom frameProcessor? 
And what can I do to debug it? My app never crashed during development.

Thanks for your help

### What happened instead?

I don't known.

### Device

Android 11, Android 10, Android 12

### VisionCamera Version

^2.12.0

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by gelfer** [comment]
#626 

you should check this out. Similar issue and still under investigation.

**Comment by mrousavy** [comment]
hmm, yes this will likely be solved with Fabric

**Comment by digitalbore** [comment]
Hi @mrousavy 

I temporarily solved the bug commenting line 417 on Camera.tsx

```
  /** @internal */
  componentWillUnmount(): void {
    if (!this.isNativeViewMounted) return;
    if (this.lastFrameProcessor != null || this.props.frameProcessor != null) {
      // this.unsetFrameProcessor(); // <-- this one
      this.lastFrameProcessor = undefined;
    }
  }
```
Does this seem like a valid temporary solution or could something worse happen? 
When do you think the bug will be fixed?

**Comment by mrousavy** [comment]
actually I think this can be removed, it will delete the memory on the native side anyways 🤔

**Comment by adamlbailey** [comment]
Also getting this same error intermittently in production: 
```
Error: Exception in HostFunction: com.mrousavy.camera.ViewNotFoundError: [system/view-not-found] The given view (ID 5647) was not found in the view manager., js engine: hermes, stack:
setFrameProcessor@1:5172069
onViewReady@1:5172162
invokeGuardedCallbackImpl@1:109371
invokeGuardedCallback@1:109428
invokeGuardedCallbackAndCatchFirstError@1:109460
executeDispatch@1:109592
executeDispatchesAndReleaseTopLevel@1:112988
forEachAccumulated@1:111074
anonymous@1:113345
batchedUpdatesImpl@1:168436
batchedUpdates@1:112905
_receiveRootNodeIDEvent@1:113182
receiveEvent@1:162582
__callFunction@1:179852
anonymous@1:178472
__guard@1:179418
callFunctionReturnFlushedQueue@1:178430
``` 

@mrousavy, let me know how I can help. Would consider a bug bounty if it was a matter of priority on your side.

**Comment by hattat-34** [comment]
It was happened to me when i put the component as a children inside of React Native's Modal component
That occurs only on android btw

To temporary solution, remove modal view and use view component

**Comment by tarikko** [comment]
```
  /** @internal */
  componentWillUnmount(): void {
    if (!this.isNativeViewMounted) return;
    if (this.lastFrameProcessor != null || this.props.frameProcessor != null) {
      // this.unsetFrameProcessor(); // <-- this one
      this.lastFrameProcessor = undefined;
    }
  }
```
Removing that line fixed it for me ! I wish that the next version will permanently fix this annoying issue.

**Comment by mrousavy** [comment]
@adamlbailey instead of putting a bug bounty on this specific issue, consider [sponsoring me](https://github.com/sponsors/mrousavy) for all the other parts of the lib that work perfectly fine :)
Also, I already fixed the issue but forgot to release a new version to npm. Doing that now (cc @tarikko)

**Comment by adamlbailey** [comment]
Sponsored with pleasure. Thanks for the good work @mrousavy!

**Comment by andrepaulo-bit** [comment]
Hello! 
Was this issue fixed in 2.12.1? 
I'm using a Camera in a modal from: https://www.npmjs.com/package/react-native-modal and https://github.com/rodgomesc/vision-camera-code-scanner but I'm still getting the same error.

**Comment by adamlbailey** [comment]
Also still getting the same error after upgrading to 2.12.1.

**Comment by PABourdais** [comment]
> It was happened to me when i put the component as a children inside of React Native's Modal component That occurs only on android btw
> 
> To temporary solution, remove modal view and use view component

same for me on 2.12.2

**Comment by gary-cohen** [comment]
Same here. I'm not sure I can remove it from the modal though.

**Comment by cjanietz** [comment]
Currently the current activity is used to recover the view instance from the view id tag.
However to deal with different view hierarchies as introduced by View Groups elsewhere in the tree it is probably better to utilize the React ViewManager for resolving the view instance.

```kotlin
val view = UIManagerHelper.getUIManager(mContext!!.get(), viewId).resolveView(viewId) as CameraView?
```
should fix this here:
https://github.com/mrousavy/react-native-vision-camera/blob/be5ec69b0292c0a20aaa63e8a9683822d370a056/android/src/main/java/com/mrousavy/camera/frameprocessor/FrameProcessorRuntimeManager.kt#L63

**Comment by mrousavy** [comment]
Does that fix the issue? If yes, shoot a PR and I'll test & merge!

**Comment by cjanietz** [comment]
> Does that fix the issue? If yes, shoot a PR and I'll test & merge!

Yes it does, for me camera now runs perfectly in a modal with a frame processor attached

**Comment by adembacajmemmo** [comment]
@mrousavy I think would be good to specify in README that users need to upgrade React Native version to 0.66.0 or above in order to use react-native-vision-camera 2.13.1 and above.

I just faced this issue, and after upgrading to 2.13.1, I couldn't build Android anymore. After you used UManager, there is resolveView which has been introduced in react-native 0.66.0 and above, so after upgrading react-native, it's working good now.

**Comment by 3imed-jaberi** [comment]
If anyone passes by here, you can fix this issue by unmounting the camera component/screen once you don't need it ...
